//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class smGood
    {
        public string GoodsID { get; set; }
        public string GoodsNo { get; set; }
        public string GoodsName { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
